import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Sidebar from './components/Sidebar/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col ">
        <div className=' fixed w-screen h-screen    bg-cover bg-center'   >
      <Image src='/image/58FB877E-F671-4333-BFAE-5149AF5DF31C.jpeg' alt='画像'  layout="fill" objectFit="cover"  />
      </div>
      <div className=" absolute z-10   items-center w-screen   font-mono text-sm lg:flex pr-0 mr-0" >
        <p className="fixed left-1  top-3 flex  w-full pl-1  border-b-4 border-r-4 border-blue-800  mb-0 pt-2 font-bold pb-2 ">  
        {/* bg-gradient-to-b from-zinc-200 backdrop-blur-2xl  dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30 */}
          A tickets to the future
          
        </p>
        <div className="fixed bottom-0 left-0 flex h-48 w-full items-end justify-center ">
          {/* bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none */}
          
        </div>
      </div>
      <div className=' z-10  absolute flex  h-screen w-screen'>
      <Sidebar />
          
      
          <div className='flex flex-col w-screen' >
            <div className=" fixed  justify-center pl-0 ml-0 pt-0 font-extrabold  text-4xl text-slate-50 ">
                <br></br>
                <br></br>
                <br></br>
                    
                <br></br>
                <br></br>
                <br></br>
                <br></br>
                
           
            </div>
        </div> 
      </div>  
      <div className=' absolute  pt-500px mt-500px pl-1/6 ml-1/6'>
      {children}
      </div>
        </main>
        
      </body>
    </html>
  )
}
